### ISSUE TITLE
NEED HELP! 

### ISSUE THREAD

**Issue by Prakrit-170807** [platinum95/SaorCon#1]
Hi! 
today I come across this software and was very interested but found no way to install it and it would be great if you are willing to offer me help. 
and hope also I am looking forward to you upgrading this client and adding me features Thanx

**Comment by platinum95** [comment]
There's currently no installer, it's just a standalone executable. You can set it to auto-run on boot in the settings menu by right-clicking on the notification-tray icon, and clicking "Settings".

**Comment by Prakrit-170807** [comment]
Hey, I was Wondering if you could help me execute this file and help me to make it run on my device.

**Comment by platinum95** [comment]
Sure, just download the release archive from the Releases page, extract the archive, and run the SaorCon.exe executable found within.
